# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dilg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dilg_father(object):
    def setupUi(self, Dilg_father):
        Dilg_father.setObjectName("Dilg_father")
        Dilg_father.resize(810, 810)
        self.dilg_wgt = QtWidgets.QWidget(Dilg_father)
        self.dilg_wgt.setGeometry(QtCore.QRect(-100, -100, 980, 980))
        self.dilg_wgt.setObjectName("dilg_wgt")

        self.retranslateUi(Dilg_father)
        QtCore.QMetaObject.connectSlotsByName(Dilg_father)

    def retranslateUi(self, Dilg_father):
        _translate = QtCore.QCoreApplication.translate
        Dilg_father.setWindowTitle(_translate("Dilg_father", "Sample"))
